local ReplicatedStorage = game:GetService("ReplicatedStorage")
local CutsceneService = require(ReplicatedStorage.Services.CutsceneService)
local DialogueService = require(ReplicatedStorage.Services.DialogueService)
local CurtainService = require(ReplicatedStorage.Services.CurtainService)
local AudioService = require(ReplicatedStorage.Services.AudioService)

return function()
	local Cutscene3 = CutsceneService:Create("Cutscene3")
	task.wait(1)
	AudioService:Add("Background", "Ambience", false, "Cutscene3Music")
	CurtainService:Hide()
	task.spawn(function()
		DialogueService:Show()

		DialogueService:Speak("Mr. Jenkins", "These darn kids! So dumb in grades yet so cunning in wit!")
		task.wait(7)
		DialogueService:Speak("Mr. Jenkins", "I must come up with a way to put an end to this madness.")
		task.wait(7)
		DialogueService:Speak("Mr. Jenkins", "Ah- Mrs. Klock!")
		task.wait(5)
		DialogueService:Speak("Mrs. Klock", "Mr. Jenkins, I was just brainstorming in the library...")
		task.wait(4)
		DialogueService:Speak("Mrs. Klock", "I think I have the most PERFECT plan!!!")
		task.wait(3)
		task.delay(1.5, function()
			AudioService:Add("Throw", "SFX", false, "Throw")
		end)
		DialogueService:Speak("Mrs. Klock", "Here... a soda. Take this.")
		task.wait(5)
		task.spawn(function()
			task.wait(0.5)
			AudioService:Add("Soda", "SFX", false, "Soda")
			task.wait(4.5)
			AudioService:Add("SodaDrop", "SFX", false, "SodaDrop")
		end)
		DialogueService:Speak("Mr. Jenkins", "...")
		task.wait(8)
		DialogueService:Speak("Mr. Jenkins", "Oh my goodness! Suddenly I feel much faster....")
		task.wait(2)
		CurtainService:Show()
	end)

	Cutscene3:Play()
	Cutscene3.Ended:Wait()
	DialogueService:Hide()
	Cutscene3:Destroy()
	AudioService:Remove("Cutscene3Music", true, 6)
	workspace.CurrentCamera.FieldOfView = 70
end