local ReplicatedStorage = game:GetService("ReplicatedStorage")
local CutsceneService = require(ReplicatedStorage.Services.CutsceneService)
local DialogueService = require(ReplicatedStorage.Services.DialogueService)
local CurtainService = require(ReplicatedStorage.Services.CurtainService)
local Players = game:GetService("Players")
local AudioService = require(ReplicatedStorage.Services.AudioService)

return function()
	local Cutscene4 = CutsceneService:Create("Cutscene4")
	task.wait(1)
	AudioService:Add("Background", "Ambience", false, "Cutscene4Music")
	CurtainService:Hide()
	task.spawn(function()
		DialogueService:Show()

		DialogueService:Speak("Mr. Jenkins", "Can't believe I have to bring these out again...")
		task.wait(6)
		DialogueService:Speak("Mr. Jenkins", "A little dusty from sitting in the basement for all those years, but these lockers ought to put a stop to the madness.")
		task.wait(8)
		DialogueService:Hide()
		task.wait(6)
		CurtainService:Show()
	end)
	Cutscene4:Play()
	local track = Cutscene4:GetTrackByRigName("EffectsDummy")
	track:GetMarkerReachedSignal("LockerSwitch"):Wait()
	local locker = script.LockerTentacles:Clone()
	locker.Parent = workspace
	local track2 = locker.AnimationController.Animator:LoadAnimation(locker.AnimationController.Animator.Animation)
	track2:Play()
	track2.Looped = true
	task.spawn(function()
		task.wait(1)
		AudioService:Add("ShowLockers", "Ambience", false, "ShowLockers")
		AudioService:Remove("Background", true, 2)
	end)
	Cutscene4.Ended:Wait()
	Cutscene4:Destroy()
	locker:Destroy()
	AudioService:Remove("ShowLockers", true, 6)
end