local ReplicatedStorage = game:GetService("ReplicatedStorage")
local CutsceneService = require(ReplicatedStorage.Services.CutsceneService)
local DialogueService = require(ReplicatedStorage.Services.DialogueService)
local CurtainService = require(ReplicatedStorage.Services.CurtainService)
local AudioService = require(ReplicatedStorage.Services.AudioService)

return function()
	local TeacherCall = CutsceneService:Create("TeacherCall")
	local PrincipalCall = CutsceneService:Create("PrincipalCall")
	local principalPhone = PrincipalCall:GetRigByRigName("Principal").PrincipalPhone
	local dummyPhone = PrincipalCall:GetRigByRigName("PrincipalEffects").DummyPhone
	principalPhone.Transparency = 1
	task.wait(1)
	AudioService:Add("PhoneCall", "Ambience", true, "PhoneCall")
	CurtainService:Hide()
	TeacherCall:Play()
	task.delay(5, function()
		AudioService:Add("Phone", "Ambience", true, "Phone")
	end)
	task.wait(10)
	DialogueService:Show()
	DialogueService:Speak("Mrs. Klock", "Come on... pick up... pick up!")
	task.wait(2)
	TeacherCall:Pause()
	PrincipalCall:Play()
	task.wait(1)
	principalPhone.Transparency = 0
	dummyPhone.Transparency = 1
	task.wait(1)
	AudioService:Remove("Phone")
	AudioService:Add("Answer", "SFX", false, "Answer")
	task.wait(1)
	DialogueService:Speak("Mr. Jenkins", "Mrs. Klock. What is it?")
	task.wait(3)
	PrincipalCall:Pause()
	TeacherCall:Resume()
	DialogueService:Speak("Mrs. Klock", "Ah, Principal Jenkins. The students have gone mad.")
	task.wait(5)
	TeacherCall:Pause()
	PrincipalCall:Resume()
	DialogueService:Speak("Mr. Jenkins", "What do you mean?!")
	task.wait(3)
	PrincipalCall:Pause()
	TeacherCall:Resume()
	DialogueService:Speak("Mrs. Klock", "They escaped detention and hid themselves in a room.")
	task.wait(5)
	DialogueService:Speak("Mr. Jenkins", "How did you let this happen?")
	TeacherCall:Pause()
	PrincipalCall:Resume()
	task.wait(3)
	PrincipalCall:Pause()
	TeacherCall:Resume()
	DialogueService:Speak("Mrs. Klock", "Because they're little con artists, that's why! Ugh... come help me catch them today, will you?")
	task.wait(7)
	TeacherCall:Pause()
	PrincipalCall:Resume()
	DialogueService:Speak("Mr. Jenkins", "Alright, will do.")
	task.delay(1.5, function()
		CurtainService:Show()
	end)
	PrincipalCall.Ended:Wait()
	TeacherCall:Destroy()
	PrincipalCall:Destroy()
	workspace.CurrentCamera.FieldOfView = 70
	AudioService:Remove("PhoneCall", true, 6)

	DialogueService:Hide()	
end